// 超时与限制相关常量

export const DEFAULT_NAVIGATION_TIMEOUT_MS = 60000;
export const DEFAULT_UI_TIMEOUT_MS = 30000;
export const DEFAULT_WORKS_TIMEOUT_MS = 45000;
export const DEFAULT_WORKS_IDLE_MS = 5000;
export const DEFAULT_COMMENTS_TIMEOUT_MS = 300000;
export const DEFAULT_COMMENTS_IDLE_MS = 5000;
export const DEFAULT_REPLY_TIMEOUT_MS = 30000;
export const DEFAULT_REPLY_SETTLE_MS = 1800;
export const DEFAULT_REPLY_TYPE_DELAY_MS = 50;
export const DEFAULT_REPLY_LIMIT = 20;
export const DEFAULT_EXPORT_LIMIT = 5000;
export const DEFAULT_REPLY_FLOW_TIMEOUT_MS = 1800000;
export const REPLY_FLOW_TIMEOUT_BUFFER_MS = 60000;
export const REPLY_FLOW_TIMEOUT_PER_PLAN_MS = 20000;
export const MAX_AUTO_REPLY_FLOW_TIMEOUT_MS = 7200000;
